site_name: VrForaging
site_description: Documentation for the VrForaging experiment
site_author: Bruno F. Cruz
copyright: 2025, Allen Institute for Neural Dynamics
repo_url: https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging
repo_name: GitHub
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: white
    accent: black
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: white
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - announce.dismiss
  - navigation.tabs
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - search.suggest
  - toc.follow
  logo: logo.svg
  favicon: icon.ico
hooks:
- docs/build.py
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          separate_signature: true
          filters:
          - '!^_'
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
          show_bases: true
          inherited_members: true
          members_order: source
        rendering:
          show_source: true
          show_root_heading: true
        selection:
          docstring_style: google
          inherited_members: true
        inventories:
        - url: https://docs.python.org/3/objects.inv
          domains:
          - py
          - std
        extensions:
        - griffe_pydantic:
            schema: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.snippets:
    base_path:
    - .
nav:
- Home: index.md