site_name: AIND VR Foraging
site_description: AIND VR Foraging behavior experiment documentation
site_author: Bruno Cruz
copyright: 2025, Allen Institute for Neural Dynamics
repo_url: https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging
repo_name: GitHub
docs_dir: docs

validation:
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: info

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/pygments.css

hooks:
  - docs/hooks.py

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - "!^_"
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_bases: true

markdown_extensions:
  - tables
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API:
    - Overview: api/index.md
    - Session: api/session.md
    - Rig: api/rig.md
    - Task Logic: api/task_logic.md
  - JSON Schemas: json-schemas.md
  - Data Contract: dataset.md
